/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_equals = 1,
  sym_tag = 2,
  sym_value = 3,
  sym_delimiter = 4,
  sym_source_file = 5,
  sym_message = 6,
  sym_field = 7,
  aux_sym_source_file_repeat1 = 8,
  aux_sym_message_repeat1 = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_equals] = "equals",
  [sym_tag] = "tag",
  [sym_value] = "value",
  [sym_delimiter] = "delimiter",
  [sym_source_file] = "source_file",
  [sym_message] = "message",
  [sym_field] = "field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_message_repeat1] = "message_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_equals] = sym_equals,
  [sym_tag] = sym_tag,
  [sym_value] = sym_value,
  [sym_delimiter] = sym_delimiter,
  [sym_source_file] = sym_source_file,
  [sym_message] = sym_message,
  [sym_field] = sym_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == 0x01 ||
          lookahead == '|') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 1:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != 0x01 &&
          lookahead != '|') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym_message] = STATE(2),
    [sym_field] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_tag] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_tag,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_field,
    STATE(3), 2,
      sym_message,
      aux_sym_source_file_repeat1,
  [14] = 4,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_tag,
    STATE(4), 1,
      sym_field,
    STATE(3), 2,
      sym_message,
      aux_sym_source_file_repeat1,
  [28] = 3,
    ACTIONS(14), 1,
      sym_delimiter,
    STATE(5), 1,
      aux_sym_message_repeat1,
    ACTIONS(12), 2,
      ts_builtin_sym_end,
      sym_tag,
  [39] = 3,
    ACTIONS(18), 1,
      sym_delimiter,
    STATE(6), 1,
      aux_sym_message_repeat1,
    ACTIONS(16), 2,
      ts_builtin_sym_end,
      sym_tag,
  [50] = 3,
    ACTIONS(22), 1,
      sym_delimiter,
    STATE(6), 1,
      aux_sym_message_repeat1,
    ACTIONS(20), 2,
      ts_builtin_sym_end,
      sym_tag,
  [61] = 3,
    ACTIONS(3), 1,
      sym_tag,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_field,
  [71] = 1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_delimiter,
  [77] = 1,
    ACTIONS(20), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_delimiter,
  [83] = 3,
    ACTIONS(3), 1,
      sym_tag,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_field,
  [93] = 2,
    ACTIONS(3), 1,
      sym_tag,
    STATE(9), 1,
      sym_field,
  [100] = 1,
    ACTIONS(29), 1,
      sym_equals,
  [104] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [108] = 1,
    ACTIONS(33), 1,
      sym_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 39,
  [SMALL_STATE(6)] = 50,
  [SMALL_STATE(7)] = 61,
  [SMALL_STATE(8)] = 71,
  [SMALL_STATE(9)] = 77,
  [SMALL_STATE(10)] = 83,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 100,
  [SMALL_STATE(13)] = 104,
  [SMALL_STATE(14)] = 108,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [12] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [14] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fix(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fix",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
