/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_tag = 1,
  sym_equals = 2,
  sym_value = 3,
  sym_delimiter = 4,
  sym_message_sep = 5,
  sym_source_file = 6,
  sym_message = 7,
  sym_field = 8,
  aux_sym_source_file_repeat1 = 9,
  aux_sym_message_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tag] = "tag",
  [sym_equals] = "equals",
  [sym_value] = "value",
  [sym_delimiter] = "delimiter",
  [sym_message_sep] = "message_sep",
  [sym_source_file] = "source_file",
  [sym_message] = "message",
  [sym_field] = "field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_message_repeat1] = "message_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tag] = sym_tag,
  [sym_equals] = sym_equals,
  [sym_value] = sym_value,
  [sym_delimiter] = sym_delimiter,
  [sym_message_sep] = sym_message_sep,
  [sym_source_file] = sym_source_file,
  [sym_message] = sym_message,
  [sym_field] = sym_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_message_sep] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == 0x01 ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != 0x01 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '^' &&
          lookahead != '|') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_message_sep);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [sym_message_sep] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_message] = STATE(9),
    [sym_field] = STATE(2),
    [sym_tag] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(7), 1,
      sym_delimiter,
    STATE(5), 1,
      aux_sym_message_repeat1,
    ACTIONS(5), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [11] = 4,
    ACTIONS(3), 1,
      sym_tag,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_field,
    STATE(15), 1,
      sym_message,
  [24] = 3,
    ACTIONS(3), 1,
      sym_tag,
    STATE(13), 1,
      sym_field,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [35] = 3,
    ACTIONS(13), 1,
      sym_delimiter,
    STATE(8), 1,
      aux_sym_message_repeat1,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [46] = 4,
    ACTIONS(3), 1,
      sym_tag,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_field,
    STATE(15), 1,
      sym_message,
  [59] = 3,
    ACTIONS(3), 1,
      sym_tag,
    STATE(13), 1,
      sym_field,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [70] = 3,
    ACTIONS(21), 1,
      sym_delimiter,
    STATE(8), 1,
      aux_sym_message_repeat1,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [81] = 3,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      sym_message_sep,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
  [91] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym_message_sep,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
  [101] = 1,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      sym_delimiter,
      sym_message_sep,
  [107] = 3,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      sym_message_sep,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
  [117] = 1,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      sym_delimiter,
      sym_message_sep,
  [123] = 3,
    ACTIONS(3), 1,
      sym_tag,
    STATE(2), 1,
      sym_field,
    STATE(15), 1,
      sym_message,
  [133] = 1,
    ACTIONS(32), 2,
      ts_builtin_sym_end,
      sym_message_sep,
  [138] = 2,
    ACTIONS(3), 1,
      sym_tag,
    STATE(13), 1,
      sym_field,
  [145] = 1,
    ACTIONS(37), 1,
      sym_equals,
  [149] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [153] = 1,
    ACTIONS(41), 1,
      sym_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 11,
  [SMALL_STATE(4)] = 24,
  [SMALL_STATE(5)] = 35,
  [SMALL_STATE(6)] = 46,
  [SMALL_STATE(7)] = 59,
  [SMALL_STATE(8)] = 70,
  [SMALL_STATE(9)] = 81,
  [SMALL_STATE(10)] = 91,
  [SMALL_STATE(11)] = 101,
  [SMALL_STATE(12)] = 107,
  [SMALL_STATE(13)] = 117,
  [SMALL_STATE(14)] = 123,
  [SMALL_STATE(15)] = 133,
  [SMALL_STATE(16)] = 138,
  [SMALL_STATE(17)] = 145,
  [SMALL_STATE(18)] = 149,
  [SMALL_STATE(19)] = 153,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [39] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fix(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fix",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
