/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ws = 1,
  sym_tag = 2,
  sym_equals = 3,
  sym_value = 4,
  sym_delimiter = 5,
  sym_line = 6,
  sym_comment = 7,
  sym_source_file = 8,
  sym_message = 9,
  sym_field = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_source_file_repeat2 = 12,
  aux_sym_message_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ws] = "ws",
  [sym_tag] = "tag",
  [sym_equals] = "equals",
  [sym_value] = "value",
  [sym_delimiter] = "delimiter",
  [sym_line] = "line",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_message] = "message",
  [sym_field] = "field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_message_repeat1] = "message_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ws] = sym_ws,
  [sym_tag] = sym_tag,
  [sym_equals] = sym_equals,
  [sym_value] = sym_value,
  [sym_delimiter] = sym_delimiter,
  [sym_line] = sym_line,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_message] = sym_message,
  [sym_field] = sym_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ws] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '\n', 11,
        '\r', 1,
        '#', 12,
        '=', 7,
        '\t', 4,
        ' ', 4,
        0x01, 10,
        '^', 10,
        '|', 10,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_ws);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x01 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '^' &&
          lookahead != '|') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != 0x01 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '^' &&
          lookahead != '|') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_line);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ws] = ACTIONS(3),
    [sym_tag] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [sym_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_message] = STATE(8),
    [sym_field] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_ws] = ACTIONS(3),
    [sym_tag] = ACTIONS(5),
    [sym_line] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_line,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym_field,
    STATE(20), 1,
      sym_message,
  [22] = 7,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(13), 1,
      sym_line,
    ACTIONS(15), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym_field,
    STATE(17), 1,
      sym_message,
  [44] = 7,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(13), 1,
      sym_line,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym_field,
    STATE(20), 1,
      sym_message,
  [66] = 7,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(13), 1,
      sym_line,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym_field,
    STATE(20), 1,
      sym_message,
  [88] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(23), 1,
      sym_line,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_comment,
  [103] = 6,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(13), 1,
      sym_line,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym_field,
    STATE(20), 1,
      sym_message,
  [122] = 5,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym_line,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(10), 1,
      aux_sym_source_file_repeat2,
  [138] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(32), 1,
      sym_delimiter,
    STATE(12), 1,
      aux_sym_message_repeat1,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      sym_line,
  [152] = 5,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      sym_line,
    STATE(5), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
  [168] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    STATE(18), 1,
      sym_field,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      sym_line,
  [182] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(38), 1,
      sym_delimiter,
    STATE(15), 1,
      aux_sym_message_repeat1,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      sym_line,
  [196] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(5), 1,
      sym_tag,
    STATE(18), 1,
      sym_field,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      sym_line,
  [210] = 5,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_line,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
  [226] = 4,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(46), 1,
      sym_delimiter,
    STATE(15), 1,
      aux_sym_message_repeat1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      sym_line,
  [240] = 5,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_line,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
  [256] = 5,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      sym_line,
    STATE(5), 1,
      aux_sym_source_file_repeat1,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
  [272] = 2,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      sym_delimiter,
      sym_line,
  [281] = 2,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      sym_delimiter,
      sym_line,
  [290] = 2,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_line,
  [298] = 3,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(56), 1,
      sym_ws,
    STATE(18), 1,
      sym_field,
  [308] = 2,
    ACTIONS(56), 1,
      sym_ws,
    ACTIONS(58), 1,
      sym_equals,
  [315] = 2,
    ACTIONS(3), 1,
      sym_ws,
    ACTIONS(60), 1,
      sym_value,
  [322] = 2,
    ACTIONS(56), 1,
      sym_ws,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 103,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 138,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 168,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 196,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 226,
  [SMALL_STATE(16)] = 240,
  [SMALL_STATE(17)] = 256,
  [SMALL_STATE(18)] = 272,
  [SMALL_STATE(19)] = 281,
  [SMALL_STATE(20)] = 290,
  [SMALL_STATE(21)] = 298,
  [SMALL_STATE(22)] = 308,
  [SMALL_STATE(23)] = 315,
  [SMALL_STATE(24)] = 322,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(7),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fix(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fix",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
